### ISSUE TITLE
#US01 Como usuario quiero registrarme con mis datos personales (email, contraseña), para poder iniciar sesión

### ISSUE THREAD

**Issue by DaniBarrios22** [Capacit-ISPC/Project_CapacIT-App#1]
- [x]  #15  #TK01Crear Activity Registro
- [x] #68
- [x] #69
- [x] #94
- [x] #95
- [x] #96
- [x] #113

**Comment by Metalderly** [comment]
Hola Dani, ahí edito las ISSUES y agrego lo que falta, cualquier cosa sobre la marcha se irán editando las que ya están y agregar las que surjan .

**Comment by FacuVillalba44** [comment]
Aplique corrección al redactar la historia de usuario para seguir la nomenclatura sugerida.
